apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-webhook
  namespace: webhook-system
  labels:
    app: resource-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resource-webhook
  template:
    metadata:
      labels:
        app: resource-webhook
    spec:
      serviceAccountName: resource-webhook
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        fsGroup: 65532

      containers:
        - name: webhook
          image: merveinal1/resource-webhook:latest
          ports:
            - name: https
              containerPort: 8443
            - name: metrics
              containerPort: 8080

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: [ALL]

          volumeMounts:
            - name: tls
              mountPath: /etc/webhook/tls
              readOnly: true

      volumes:
        - name: tls
          secret:
            secretName: resource-webhook-tls
